spring.application.name=student_server
spring.datasource.url=jdbc:postgresql://localhost:5432/springKP
spring.datasource.username=postgres
spring.datasource.password=0302
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  # Можно поставить "create" для первого запуска
spring.jpa.show-sql=true
